### ISSUE TITLE
custom fields should be displayed in audit detail 

### ISSUE THREAD

**Issue by anteneh72** [anteneh72/UltimoTLS#14]
When showing audit detail, we should also show custom fields that can be added by client. 

Solutions: add custom field in the data structure and display in audit details. On the UI implement ng-repeat for this.

**Comment by anteneh72** [comment]
Dataformat for customFields (see below):

{
    "envid": "QA",
    "application": "JAVA",
    "interface1": "ValidateDunsNumber",
    "hostname": "java.server1.com",
    "transactionDomain": "CRM",
    "transactionType": "Order",
    "transactionId": "LZY2BSWL1Z",
    "severity": "Warning",
    "errorType": "technical",
    "category": "",
    "timestamp": "2015-06-22T13:36:54",
    "activityName": "",
    "processID": "",
    "engineName": "",
    "trackingInfo": "",
    "stackTrace": "Duis eu reprehenderit Lorem consectetur est id. Laborum non minim sit do nostrud irure adipisicing ipsum voluptate. Culpa cupidatat in esse aliquip est non excepteur aliqua dolore enim enim ut veniam duis. Pariatur sint cillum officia consequat qui labore. Aute anim amet id deserunt exercitation anim eu laborum laboris qui nisi veniam. Fugiat occaecat sunt culpa consectetur aliquip ex esse tempor est.\r\n",
    "msg": "Cillum nisi quis ut quis nisi officia ad nostrud fugiat minim occaecat. Non veniam aliqua aliquip minim anim. Do et occaecat eu cillum eu fugiat fugiat velit consequat anim culpa. Exercitation est exercitation eu aliquip consequat id ut non in consequat non do reprehenderit.\r\n",
    "msgCode": "",
    "class": "",
    "processStack": "",
    "dataLocation": "",
    "interfaceData": "",
    "notification": "",
    "status": "Failed",
    "exceptionFlag": "1",
    "customField": {
               "Account Info" : "Customer", 
               "Account ID": "12345"
            }
  }

**Comment by fernandez7108** [comment]
Added ng-repeat object.customFields to the end of the dataBasePage Modal to show name value pairs  if they exist.  Can be tested in Java->ValidateCustomerAddress
